#!/bin/bash

REPO="$1"
QUEUEDIR="$2"
PREFIX="$3"
CID="$4"
PUBLISHER="$5"
set -e
echo "starting transaction for publish in $REPO"
if ! cvmfs_server transaction $REPO; then
    echo "transaction start failed, trying abort and transaction again"
    cvmfs_server abort -f $REPO
    cvmfs_server transaction $REPO
fi
SUBPATH="/cvmfs/$REPO/$PREFIX/$CID"
if [ "$PREFIX" = "ts" ]; then
    echo "touching $SUBPATH"
    mkdir -p "${SUBPATH%/*}"
    echo "$PUBLISHER" > $SUBPATH
else
    echo "extracting into $SUBPATH"
    mkdir -p "$SUBPATH"
    if ! tar -C "$SUBPATH" -xf "$QUEUEDIR/$CID"; then
        echo "extraction failed, aborting"
        cvmfs_server abort -f $REPO
        exit
    fi
    touch $SUBPATH/.cvmfscatalog
    echo "$PUBLISHER" > $SUBPATH/.publisher
fi
echo "publishing $SUBPATH"
cvmfs_server publish $REPO
echo "done with $CID"
